name: neuroeraa
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  lottie: ^3.3.1
  google_fonts: ^6.1.0
  cupertino_icons: ^1.0.8
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.2
  path_provider_android: ^2.2.1
  google_sign_in: ^6.1.5
  cloud_firestore: ^5.6.6
  http: ^1.4.0
  intl: ^0.18.1



  font_awesome_flutter: ^10.5.0
  firebase_vertexai: ^1.6.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/animations/cat1.json
    - assets/images/google_logo.webp
    - assets/animations/brain1.json
    - assets/animations/forum.json
    - assets/animations/askai.json
    - assets/animations/therapy.json
    - assets/animations/learn.json

