// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDK9kj3P8-WY-HyrJB-A4ImvE61dwiqwDw',
    appId: '1:412058117680:web:da23a7c5acbe1ef025eff5',
    messagingSenderId: '412058117680',
    projectId: 'neuroeraa',
    authDomain: 'neuroeraa.firebaseapp.com',
    storageBucket: 'neuroeraa.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA8Wafs-p71ZKD5pr-fJPlc4FdEpiYK_xg',
    appId: '1:412058117680:android:64d5be74aa2ac39325eff5',
    messagingSenderId: '412058117680',
    projectId: 'neuroeraa',
    storageBucket: 'neuroeraa.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCHdJAWtJa61AL3dxuM6I5GeDDz2tSksaM',
    appId: '1:412058117680:ios:12d81f4d46d5f0e625eff5',
    messagingSenderId: '412058117680',
    projectId: 'neuroeraa',
    storageBucket: 'neuroeraa.firebasestorage.app',
    iosClientId: '412058117680-b1jg5voml15shlpj6q6l4t5jb05clsv7.apps.googleusercontent.com',
    iosBundleId: 'com.example.neuroeraa',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCHdJAWtJa61AL3dxuM6I5GeDDz2tSksaM',
    appId: '1:412058117680:ios:12d81f4d46d5f0e625eff5',
    messagingSenderId: '412058117680',
    projectId: 'neuroeraa',
    storageBucket: 'neuroeraa.firebasestorage.app',
    iosClientId: '412058117680-b1jg5voml15shlpj6q6l4t5jb05clsv7.apps.googleusercontent.com',
    iosBundleId: 'com.example.neuroeraa',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDK9kj3P8-WY-HyrJB-A4ImvE61dwiqwDw',
    appId: '1:412058117680:web:001064fccf4c5cf925eff5',
    messagingSenderId: '412058117680',
    projectId: 'neuroeraa',
    authDomain: 'neuroeraa.firebaseapp.com',
    storageBucket: 'neuroeraa.firebasestorage.app',
  );
}
